### PR TITLE
Feature/config file

### PR DESCRIPTION
**Pull request by theRealSuperMario**
Hi,

I was trying to submit to arXiv and came across the great arxiv-latex-cleaner tool to help me get my paper onto arXiv. Unfortunately, the tool did not have all the features I needed, so I decided to just add everything that I needed into it.

The features include:
- support for reading a config file which contains the settings used for the cleaner
- support for performing arbitrary regex searches and inserting the captured groups into defined templates
- verbose output for debugging

I was not sure which python formatter you guys use, so I guess I will have to make a formatting commit at the end.
Furthermore, I am not sure how to increment the version number correctly.

Let me know what you think. I think now that the functionality is there, some functionality could be absorbed into the more general regex substitution pipeline. For example, `_remove_commands` and `_remove_patterns` could be transformed into an empty insertion. This would have the advantage that the pipeline is more transparent, flexible, and in general supports multiline expressions.

Cheers 🍺

### CODE REVIEW

**Comment by theRealSuperMario** [comment]
@googlebot I signed it!

**Comment by jponttuset** [comment]
Thank you very much for this PR, @theRealSuperMario !

> Unfortunately, the tool did not have all the features I needed, so I decided to just add everything that I needed into it.
Imagine a world where everyone would act like you 😍

> I was not sure which python formatter you guys use
Do not worry about the formatting, I'll pass it through our auto-formatting and commit the changes myself before merging.

> some functionality could be absorbed into the more general regex substitution pipeline. For example, _remove_commands and _remove_patterns could be transformed into an empty insertion. This would have the advantage that the pipeline is more transparent, flexible, and in general supports multiline expressions.
Absolutely! If you still have energy, feel free to send us a new PR, otherwise I'll mark it as future improvement. I'll merge it as is for now.

**Comment by theRealSuperMario** [comment]
Sounds good.

> Do not worry about the formatting, I'll pass it through our auto-formatting and commit the changes myself before merging.

It would be great to have the formatting specification available so that I can get a nice and clean diff output.


> If you still have energy, feel free to send us a new PR, otherwise I'll mark it as future improvement. I'll merge it as is for now.

I think that will have to wait for a bit, but you can create an issue and assign me to it so that it gets added to my inbox.


Cheers 🍻

**Comment by jponttuset** [comment]
Hi @theRealSuperMario,

I did a formatting pass on the code. To check the style, see https://github.com/google/yapf.

It seems now you need to consent to my changes for me to merge.

Best,

**Comment by theRealSuperMario** [comment]
@googlebot I consent

**Comment by theRealSuperMario** [comment]
@googlebot I consent.

**Review by theRealSuperMario — COMMENTED** [review]
@googlebot I consent.

**Comment by theRealSuperMario** [comment]
Not sure if I am doing it correctly ...

**Comment by jponttuset** [comment]
@googlebot I consent.

**Comment by jponttuset** [comment]
> Not sure if I am doing it correctly ...

You are, but it seems I also had to consent... due to my google vs gmail accounts.

**Pull request merged**
