### PR TITLE
fixes google-research/arxiv-latex-cleaner#22

### PR DESCRIPTION
**Pull request by aditya95sriram**
Now searches for exact full path of images and other non-tex when checking for references. Additionally the extension is optional for images (and not for other non-tex) during this reference search.

The specific regex used accounts for possible whitespace and could match invalid TeX as well. But that is not the tool's fault/responsibility.

### CODE REVIEW

**Comment by aditya95sriram** [comment]
@googlebot I signed it!

**Comment by aditya95sriram** [comment]
@googlebot I fixed it.

**Comment by jponttuset** [comment]
Hi @aditya95sriram,
I wonder if you could have a look at my review and address it?
Thanks!

**Comment by aditya95sriram** [comment]
Sorry, had lost track of this. Pulled in the latest version into my bugfix branch. Revisiting some of my old comments from #22 , I'm still concerned about the behavior when dealing with the scenario mentioned [here](https://github.com/google-research/arxiv-latex-cleaner/issues/22#issuecomment-648129420). 

Is it ok to include some potential images even if we are unsure of their usage, to be on the safer side? Maybe they end up actually being used due to `graphicspath`?

The behavior as of now, only looks at absolute paths. This is because the regex that I had committed last only allows for `{` before the path name and not `os.path.sep` as you had suggested.

**Comment by aditya95sriram** [comment]
I suppose the only way to deal with this (without getting into `graphicspath`) is as follows:

> For each file `path/to/img_name.jpg` that we encounter in the file tree, we only check for the occurrence of the string `img_name` in the contents of the tex files

**Comment by aditya95sriram** [comment]
Ok, I think I've figured it out. My previous message still holds, except that any fragment of the prefix path is allowed to appear between `{` and the root (i.e. `img`)
 
Here's the regex when checking for file `path/to/img.ext` [[Regex unit tests](https://regex101.com/r/OKnXDS/2)] [[Visual explanation](https://www.debuggex.com/r/DNeC1WvH3Y7V1u9p)]

    \{[\s%]*((path/)?to/)?img(\.ext)?[\s%]*\}

**Comment by aditya95sriram** [comment]
Pushed with new tests (might add more later). I figure `im1.png` as it shares a prefix with `im1_included.png` and its good to check that it does not get copied.

**Comment by jponttuset** [comment]
Thanks @aditya95sriram (and P. R. Vaidyanathan)!
That was brilliant!

**Pull request merged**
